library(shiny)
library(shinydashboard)
library(shinymanager)
library(ggplot2)
library(plotly)
library(dplyr)
library(readr)
library(caret)
library(randomForest)
library(blastula)
library(DT)

source("../R/auth.R")
source("../R/data_ingestion.R")
source("../R/data_processing.R")
source("../R/ml_models.R")
source("../R/visualization.R")
source("../R/notifications.R")
source("../R/utils.R")

climate_data <- load_climate_data("../data/sample_climate_data.csv")
